import os
from dotenv import load_dotenv
from openai import OpenAI
from services.audio_manager import convert_from_mp3_to_ogg

"""
Environment variables for connecting to OpenAI
"""
load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")


"""
File path to save the audio file generated from Whisper
"""
AUDIO_WHISPER_PATH = "temp_files/speech.mp3"


"""
Singleton for OpenAI client where it initialised once and used across stages
that require OpenAI's API
"""
openai_client = OpenAI(api_key=OPENAI_API_KEY)


"""
Returns the OpenAI client singleton

Parameters: No parameters

Returns:
    The OpenAI client required for OpenAI calls
"""
def get_openai_client():
    return openai_client


"""
Runs the chat completion API to produce an output generated by GPT

Parameters:
    - model: Model to use for chat completions API
    - messages: Messages that act as context
    - temperature: Temperature for randomness
  
Returns:
    - response: Text response generated
"""
def generate_text_gpt(model, messages, temperature=1):
    # Run the chat completions API
    raw_response = openai_client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=temperature
    )
    response = raw_response.choices[0].message.content

    # Return the text output
    return response


"""
Produces a OGG file that is a voice-over for the given input text using
Whisper API. This is a text-to-speech function.

Parameters:
    - input_text: The text to be voiced over

Returns:
    ogg_file_path: File path of the generated OGG audio
"""
def generate_speech_whisper(input_text):
    # Step 1: Generate MP3 file from Whisper
    print(input_text)
    client = get_openai_client()
    with client.audio.speech.with_streaming_response.create(
        model="tts-1",
        voice="shimmer",
        input=input_text,
    ) as response:
        response.stream_to_file(AUDIO_WHISPER_PATH)

    # Step 2: Convert MP3 file to OGG file
    ogg_file_path = convert_from_mp3_to_ogg(AUDIO_WHISPER_PATH)

    # Step 3: Return file path
    return ogg_file_path

